### ISSUE TITLE
Armar Grupos y Definir Idea de la Aplicación

### ISSUE THREAD

**Issue by catrielmuller** [lametro/programacion-4-2015#23]

**Comment by catrielmuller** [comment]
Grupo: Profesor

Integrantes:
- Catriel Müller

**Comment by PixelArg** [comment]
Grupo: PixelEsp
Integrantes: Nicolas Galdo, Ariadna Guitian, Agustin Azar

Descripción: 
Aplicación basada en un sitio web.

**Comment by gino0110** [comment]
Nombre de la app: App para boliche
Integrantes: 
*Martin Leidreiter @Leidreiter 
*Gino Bernasconi

Descripción;
Una app diseñada para un boliche en la que se interactue con el usuario a través de promociones, info, juegos. etc

**Comment by rodrigoliborci** [comment]
grupo: geolocalizacion  
integrante: rodrigoliborci

**Comment by hernanbaigorria** [comment]
Nombre de grupo: Se juega
Participantes: @salomonelias @fedemiguez @Franconeri85 @hernanbaigorria
Resumen: Aplicación para organizar partidos de futbol

**Comment by rodriherreria** [comment]
Grupo: GeoAlquiler
Integrantes: @FrancoMeriles, @ignaciopiai   y @rodriherreria
Resumen: Aplicación para alquilar departamentos, oficina, negocio o casa por geoposicionamiento.

**Comment by LuPicin** [comment]
Nombre del Grupo  DiabetAppi
Integrantes del grupo:  @florseg (Florencia Segovia ) y Picin Luciana. 
Brief 
Nuestra Aplicación esta pensada para ayudar a personas que tenga  diabetes. 
La idea es poder ayudar las personas con este problemas de saluda,  con su enfermedad en estado avanzado, donde ellos pesan la cantidad de comida que van a consumir y de ahí tienen que calcular la cantidad de insulina que deben inyectarse. La idea es que esta aplicación realice esas cuentas sola y lleve un control del usuario.

**Comment by m-gmz** [comment]
Grupo: Doggies

Integrantes:
Pablo Ciruelos @pciruelos
Marinela Gomez @m-gmz 
Agustin Verra @AgustinVerra

Brief del proyecto:
1)Realidad aumentada. leer código o pin y mostrar producto.

2)Aplicación móvil contributiva de recetas de comida. tiene para elegir varios filtros como tiempo, ingredientes, etc...

https://bitbucket.org/doggieslametro/realidad-aumentada

**Comment by JuampaBlaskovich** [comment]
Nombre Grupo:
*Hijos de Odin

Integrantes:
*Blaskovich Juan Pablo
*Caravajal Lucas
*Rivera Ezequiel
*Vanegas Francisco

Brief_Servicios_
La aplicación va a ser diseñada como una librería de servicios, la idea es que las personas anoten sus emprendimientos dentro de la aplicacion. Servicios básicos que ya no son de popularidad, y que siempre nos dan la interrogante de donde poder conseguirlos. Ejemplo: plomero, electricista, mecanico, gasista, etc. Esos empleos sobreestimados, en donde las personas van a poder calificar el servicio y dejar un comentario.
Dependiendo de la puntuacion, calificación y comentarios positivos vas a estar ordenados en un ranking, como los recomendados, mejores valorados y mejor calificado.
