### ISSUE TITLE
Que SDK instalo

### ISSUE THREAD

**Issue by AgustinVerra** [lametro/programacion-4-2015#28]
Hola profe, queria saber cual paquete instalo. o cual me recomienda. win 8.1; 64 bits

![sdk](https://cloud.githubusercontent.com/assets/13700514/9572664/c4994cf0-4f88-11e5-969e-6f7198441328.jpg)

Gracias, saludos

**Comment by catrielmuller** [comment]
@AgustinVerra, por lo que veo ya tienes instalado los SDK requeridos ya que son los que te instala automáticamente el Android Studio.
Con respecto a las Imágenes te recomiendo que te instales:
- ARM EABI v7a System Image
- Intel X86 Atom System Image
  Y los mismos de la versión 5.1.1 (Api 22)
