### ISSUE TITLE
npm should be run outside of the node repl

### ISSUE THREAD

**Issue by pciruelos** [lametro/programacion-4-2015#29]
Hola! tuve este problema al instalar cordova,ionic,etc... me salia 

npm should be run outside of the node repl.....bla bla

busque la solución y decía que lo instalara desde el node command prompt.

hice bien?

**Comment by catrielmuller** [comment]
Seguramente esta intentando usar NPM desde la consola interactiva de NodeJS.

Tienes que ejecutar NPM desde una consola Base, para ello abre el menú inicio y ejecuta "cmd". Desde esa terminal vas a poder usar npm sin problemas.

![npminsidenode](https://cloud.githubusercontent.com/assets/2272323/9593650/a4268a2e-5027-11e5-9741-853a8fd3ea4c.png)
