### ISSUE TITLE
Consulta npm -g http-server

### ISSUE THREAD

**Issue by rodriherreria** [lametro/programacion-4-2015#30]
Hola profe estuvimos creando un proyecto con el nodejs y fuimos poniendo esto:

-cordova create hola org.lametro.app.hola HolaMundo
-cd hola
-npm -g http-server

con esta ultima linea de codigo nos tira error

![captura](https://cloud.githubusercontent.com/assets/13700507/9737256/2070142a-561c-11e5-94cd-c16a4a56fa6c.PNG)

**Comment by catrielmuller** [comment]
Hola Rodrigo.
El comando para instalar le falta la acción, quedando así.
npm install -g http-server

Verificalo si te funciona y cerra el TK.
Saludos.
