### ISSUE TITLE
Error run Android

### ISSUE THREAD

**Issue by ignaciopiai** [lametro/programacion-4-2015#31]
Profe como le va, estamos teniendo un error al intentar correr el proyecto en Android, cuando ponemos cordova run android nos sale este error, tenemos la plataforma instalada ya de android. 
Y cuando queremos desde el celular habilitar el modo desarrollador no pasa nada.
Ya tenemos instalado los drivers a través del android studio
![error](https://cloud.githubusercontent.com/assets/13700499/9879849/7608b120-5b9f-11e5-9ebb-c7904f38f7f5.png)

Tenemos el mismo error cuando queremos correr el browser, la plataforma ya esta instalada tambien.
![image](https://cloud.githubusercontent.com/assets/13700499/9880134/b969e1b8-5ba0-11e5-9c1e-3d70ff23b2f5.png)

**Comment by catrielmuller** [comment]
Con respecto al problema de Android tienen que instalar el SDK 22 te adjunto una imagen de que seguramente te falta instalarlo en el SDK Manager
![sdk22](https://cloud.githubusercontent.com/assets/2272323/9884202/e5af21ac-5bb4-11e5-8f4a-ea27993ae589.png)

Seguramente tenes instalado el 23 por que te lo instalo el android studio automaticamente pero no tenes el 22.

con respecto a ejecutarlo en el browser, tienen que hacerlo con el siguiente comando.
"ionic serve" o "cordova serve"

**Comment by catrielmuller** [comment]
Te pido que me comentes si se soluciono el problema con esto, asi cerramos el Issue

**Comment by ignaciopiai** [comment]
Profe sigue saliendo el mismo error, instalamos el sdk build tool 22.0.1
![image](https://cloud.githubusercontent.com/assets/13700499/9917375/8a4c7cea-5c97-11e5-9cd0-b070dde93df5.png)

**Comment by catrielmuller** [comment]
Pueden copiarme todo lo que les muestra luego de ejecutar el RUN.

**Comment by ignaciopiai** [comment]
![image](https://cloud.githubusercontent.com/assets/13700499/9918036/15aec9a2-5c9b-11e5-8d48-05570fefa631.png)
![image](https://cloud.githubusercontent.com/assets/13700499/9918056/234131e0-5c9b-11e5-84ca-f8874cae2af9.png)
Esos son todas las lineas que nos muestra luego de ejecutar el run android

**Comment by catrielmuller** [comment]
Por que están usando Cordova en vez de Ionic?

**Comment by FrancoMeriles** [comment]
tambien probamos con ionic build android y ionic run android nos sigue tirando error pero ahora vamos a probar en otra pc capaz que ese es el problema

**Comment by LuPicin** [comment]
somos varios con ese error !!

El 16 de septiembre de 2015, 19:46, FrancoMeriles notifications@github.com
escribió:

> tambien probamos con ionic build android y ionic run android nos sigue
> tirando error pero ahora vamos a probar en otra pc capaz que ese es el
> problema
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lametro/programacion-4-2015/issues/31#issuecomment-140916020
> .

## 

Picin, Luciana

**Comment by catrielmuller** [comment]
Prueben por las dudas hacer un:
ionic platform rm android
ionic platform add android

**Comment by rodriherreria** [comment]
![image](https://cloud.githubusercontent.com/assets/13700507/9922676/c3436c28-5cc1-11e5-8cdf-3838efbd2388.png)

ami me acaba de tirar este error

**Comment by gino0110** [comment]
Hola gente! yo también tenía ese problema. Después de renegar, lo que hice fue instalar la API 22 completa. Ahí recién me anduvo. Ademas hay que asegurarse de tener los driver del celu instalados correctamente. Por ultimo con "ionic run android" pude hacerla andar. No se si será la solución, pero a mi me funcionó.

![sin titulo](https://cloud.githubusercontent.com/assets/13700511/9922847/d2d5e7cc-5cc3-11e5-832f-58824c83c0c1.png)

**Comment by catrielmuller** [comment]
Vamos a hacer lo siguiente a que hora pueden hacer un hangout público todos los que tengan problemas para montar el entorno?

**Comment by JuampaBlaskovich** [comment]
Yo estoy igual. Me tira error cuando intento correr el android en el telefono

**Comment by FrancoMeriles** [comment]
Gracias gino0110 probamos con eso y lo que dijo el profe ionic platform rm android / ionic platform add android y pudimos buildear la app, listo
