### ISSUE TITLE
No puedo Instalar el Android Studio

### ISSUE THREAD

**Issue by JuampaBlaskovich** [lametro/programacion-4-2015#32]
![error sdk](https://cloud.githubusercontent.com/assets/13700584/9894541/3f17c67c-5bfb-11e5-8b44-9514afccd263.JPG)

**Comment by catrielmuller** [comment]
JavaFX no es JDK lo que tu tienes que descargar es el JDK. (Adjunto Imagen
![jdk](https://cloud.githubusercontent.com/assets/2272323/9894891/a0bec660-5bff-11e5-8e3c-b145b18c0cdd.png)
)

Verifica de bajar Windows x86 o Windows x64 dependiendo del Sistema Operativo que tengas.

**Comment by JuampaBlaskovich** [comment]
Uh joya! Me salio. Gracias =)

**Comment by JuampaBlaskovich** [comment]
Mentira, no me salio. Me salto esto cuando lo estaba por ejecutar

![erroorrr](https://cloud.githubusercontent.com/assets/13700584/9895696/0ebb8bb8-5c09-11e5-9aac-c021692485dd.JPG)

**Comment by catrielmuller** [comment]
Probaste reiniciar la pc?

**Comment by JuampaBlaskovich** [comment]
Si profe no anda, me sigue saliendo el mismo problema

**Comment by catrielmuller** [comment]
Vamos a hacer lo siguiente a que hora pueden hacer un hangout público todos los que tengan problemas para montar el entorno?

**Comment by JuampaBlaskovich** [comment]
Ahi pude :baby_bottle:

**Comment by JuampaBlaskovich** [comment]
Ahi pude =D
