### ISSUE TITLE
Error con run android

### ISSUE THREAD

**Issue by AgustinVerra** [lametro/programacion-4-2015#33]
Hola Catriel. me sale este error despues de poner los PATH que me dijiste bien. Que puede ser?
![error](https://cloud.githubusercontent.com/assets/13700514/9977432/3ad666aa-5ede-11e5-89e5-8b14fc85f1dc.jpg)

**Comment by AgustinVerra** [comment]
@catrielmuller

**Comment by catrielmuller** [comment]
@AgustinVerra Recorda pasarme el nuevo error que te tira cuando intentas hacer un:

ionic platform add android

**Comment by AgustinVerra** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/13700514/10207528/473d864e-67a3-11e5-8439-570466a0bab0.jpg)

**Comment by catrielmuller** [comment]
http://forum.ionicframework.com/t/add-platform-android-error/27523/5
