### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by rodriherreria** [lametro/programacion-4-2015#34]
Profe nos salta este error cuando entramos al index.php, no encontramos el error.

![captura](https://cloud.githubusercontent.com/assets/13700507/10167802/78ca1f3c-66a0-11e5-96d9-508249bb18af.PNG)

**Comment by catrielmuller** [comment]
Porque no hay ninguna función que represente el index, agregen lo siguiente:

``` php
$app->get('/', function () use ($app) {
    $app->render(200,array('msg' =>'API INDEX'));
});
```
