### ISSUE TITLE
Se busca Profesor PHP!!!

### ISSUE THREAD

**Issue by pciruelos** [lametro/programacion-4-2015#37]
hola! abro este issue para que aquel que conozca  un profesor particular o usted profe si tiene algún conocido mejor, que pase el dato, algunos todavía tenemos problemas que vienen desde php1 ( yo ) que no se solucionan viendo unos tutoriales de youtube jaja. eso nada mas, saludos!

**Comment by JuampaBlaskovich** [comment]
Yo conozco a un amigo que enseña. Ahi te paso el numero 3512385905
