### ISSUE TITLE
No podemos instalar Whitelist

### ISSUE THREAD

**Issue by rodriherreria** [lametro/programacion-4-2015#38]
Hola profe, tenemos nuestro problema de google map que no se puede ver en diapositivos ni en un emulador que usamos (bluestacks), creemos que puede ser eso ed Whitelist xq intentamos insertar una imagen a traves de un src=http y no la muestra en el celular. 

Fuimos aca http://docs.ionic.io/docs/cordova-whitelist e intentamos pero es a traves de git asi que lo instalamos.

![error1](https://cloud.githubusercontent.com/assets/13700507/10312845/39ebefc4-6c23-11e5-9c3d-b20fb68739d3.PNG)

Pero igual nos sigue tirando error aunque la agregamos a las PATH nos sigue tirando que no reconoce el comando git.. no hay otra forma de instalar Whitelist ?

![path](https://cloud.githubusercontent.com/assets/13700507/10312941/9cc2d176-6c23-11e5-8011-efc5edfa5c9b.PNG)

**Comment by catrielmuller** [comment]
Es por que te falta instalar GIT, puedes bajar el binario desde aqui:
https://git-scm.com/download/win
Y agregar el path en la variable de entorno "PATH".

**Comment by FrancoMeriles** [comment]
https://blog.nraboy.com/2014/11/using-slide-boxes-tabs-ionic-framework-apps/
