### ISSUE TITLE
Videos de Clases

### ISSUE THREAD

**Issue by fedemiguez** [lametro/programacion-4-2015#41]
Profe puede subir los videos de las ultimas dos clases, tengo un problema con el option y no me acuerdo como lo habias solucionado, en el primer video se termina justo con el error ese.

Gracias!

![image](https://cloud.githubusercontent.com/assets/13700491/10624426/83a37ce4-776e-11e5-9718-e5290f79bfc4.png)

**Comment by rodriherreria** [comment]
tienen que agregar esto en el index del api

header("Access-Control-Allow-Origin: *");

**Comment by florseg** [comment]
Genial gracias rodri

**Comment by catrielmuller** [comment]
Quedo actualizado en la Wiki del Proyecto 
https://github.com/lametro/programacion-4-2015/wiki
