### ISSUE TITLE
Error con Method Put and Delete

### ISSUE THREAD

**Issue by FrancoMeriles** [lametro/programacion-4-2015#42]
Hola profe, ya pudimos subir la api a heroku con la BD. Con el administrador podemos recibir bien los datos, pero cuando queremos acutalizar o borrar un usuario nos pasa este error

![image](https://cloud.githubusercontent.com/assets/13789088/10769229/b2b0c668-7cc3-11e5-96b9-ab7e870c738e.png)

aca esta el repositorio de la api

https://github.com/rodriherreria/api-geoalquiler

lo comparamos con el suyo y nosotros le tuvimos que agregar 
header("Access-Control-Allow-Origin: *"); para que funcione

aca esta el repositorio en heroku

api-geoalquiler.herokuapp.com/index.php/usuarios

**Comment by fedemiguez** [comment]
si yo tambien tengo el mismo error todavia no pude avanzar ami me pasa lo mismo pero en el localhost! 
![image](https://cloud.githubusercontent.com/assets/13700491/10770036/faa74aba-7cc7-11e5-9c73-5343f734f921.png)

**Comment by catrielmuller** [comment]
agregen este archivo a su proyecto 

https://github.com/catrielmuller/api-prog4/blob/master/.htaccess

**Comment by fedemiguez** [comment]
me sale otro error

![image](https://cloud.githubusercontent.com/assets/13700491/10770619/09133e94-7ccb-11e5-873b-0d9b64c26658.png)

**Comment by catrielmuller** [comment]
@fedemiguez abri una issue diferente ya que no es el mismo error.

**Comment by rodriherreria** [comment]
Anda bien ahora agregando el archivo .htaccess , gracias profe !
