### ISSUE TITLE
error con archivo .htaccess

### ISSUE THREAD

**Issue by fedemiguez** [lametro/programacion-4-2015#43]
cuando agrego el archivo htacces a la carpeta no me responde ningun comando ni get ni nada 

![image](https://cloud.githubusercontent.com/assets/13700491/10770838/2f5696b8-7ccc-11e5-926b-b118e255ee1a.png)

**Comment by catrielmuller** [comment]
podrias subir la API a un server de Heroku y pasar el link del proyecto en un GIT para ver el codigo

**Comment by hernanbaigorria** [comment]
https://github.com/fedemiguez/apisejuega esta es la url de la api, cuando pusimos la variable path de heroku, dejo de funcionar la compu, no entra a ningun programa asi que no podemos seguir con esa parte por ahora

**Comment by catrielmuller** [comment]
Te deje un pull request sobre tu repositorio: https://github.com/fedemiguez/apisejuega/pull/1

Si no te funciona el Htaccess que coloque es por que no tienes habilitado el modulo de headers en tu apache.

https://github.com/h5bp/server-configs-apache/wiki/How-to-enable-Apache-modules

**Comment by catrielmuller** [comment]
wampmanager -> Apache -> Apache modules -> headers_module

**Comment by catrielmuller** [comment]
@fedemiguez pudiste resolver este inconveniente?

**Comment by fedemiguez** [comment]
si cuando lo subi a heroku no me tiro mas ese error, lo que me pasa ahora es que me salta otro error cuando quiero crear un usuario, pero abro otra issue para eso
