### ISSUE TITLE
Error para crear un usuario (WARNING: Illegal string offset 'name')

### ISSUE THREAD

**Issue by fedemiguez** [lametro/programacion-4-2015#45]
Hola profe, estamos teniendo un error a la hora de crear un usuario es solo con esa consulta, el problema existe desde la app y desde el postman, antes funcionaba y despues de modificar la api empezo a tirar el problema

![image](https://cloud.githubusercontent.com/assets/13700491/10891126/e6356cd0-817a-11e5-8bc9-26a3143412e8.png)

aca el error en postman 

![image](https://cloud.githubusercontent.com/assets/13700491/10891204/49b13bfe-817b-11e5-998c-c5d8df4b3897.png)

aca dejo el codigo de la api

<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(-1);

require 'vendor/autoload.php';
require 'Models/User.php';

$app = new \Slim\Slim();

$app->config('databases', [
    'default' => [
        'driver'    => 'mysql',
        'host'      => 'us-cdbr-iron-east-03.cleardb.net',
        'database'  => 'heroku_b2562bab37645c3',
        'username'  => 'bd90c798d775ac',
        'password'  => '9221123b',
        'charset'   => 'utf8',
        'collation' => 'utf8_general_ci',
        'prefix'    => ''
    ]
]);

$app->add(new Zeuxisoo\Laravel\Database\Eloquent\ModelMiddleware);
$app->view(new \JsonApiView());
$app->add(new \JsonApiMiddleware());
$app->add(new \Slim\Middleware\ContentTypes());

$app->options('/(:name+)', function() use ($app) {
    $app->render(200,array('msg' => 'API SeJuega'));
});

$app->get('/', function () use ($app) {
    $app->render(200,array('msg' => 'API SeJuega'));
});
$app->get('/usuario', function () use ($app) {
    $db = $app->db->getConnection();
    $users = $db->table('users')->select('id', 'name')->get();
    $app->render(200,array('data' => $users));
});
$app->post('/usuario', function () use ($app) {
    $input = $app->request->getBody();
    $name = $input['name'];
    if(empty($name)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'name is required',
        ));
    }
    $password = $input['password'];
    if(empty($password)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'password is required',
        ));
    }
    $email = $input['email'];
    if(empty($email)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'email is required',
        ));
    }
    $user = new User();
    $user->name = $name;
    $user->password = $password;
    $user->email = $email;
    $user->save();
    $app->render(200,array('data' => $user->toArray()));
});
$app->put('/usuario/:id', function ($id) use ($app) {
    $input = $app->request->getBody();

```
$name = $input['name'];
if(empty($name)){
    $app->render(500,array(
        'error' => TRUE,
        'msg'   => 'name is required',
    ));
}
$password = $input['password'];
if(empty($password)){
    $app->render(500,array(
        'error' => TRUE,
        'msg'   => 'password is required',
    ));
}
$email = $input['email'];
if(empty($email)){
    $app->render(500,array(
        'error' => TRUE,
        'msg'   => 'email is required',
    ));
}
$user = User::find($id);
if(empty($user)){
    $app->render(404,array(
        'error' => TRUE,
        'msg'   => 'user not found',
    ));
}
$user->name = $name;
$user->password = $password;
$user->email = $email;
$user->save();
$app->render(200,array('data' => $user->toArray()));
```

});
$app->get('/usuario/:id', function ($id) use ($app) {
    $user = User::find($id);
    if(empty($user)){
        $app->render(404,array(
            'error' => TRUE,
            'msg'   => 'user not found',
        ));
    }
    $app->render(200,array('data' => $user->toArray()));
});
$app->delete('/usuario/:id', function ($id) use ($app) {
    $user = User::find($id);
    if(empty($user)){
        $app->render(404,array(
            'error' => TRUE,
            'msg'   => 'user not found',
        ));
    }
    $user->delete();
    $app->render(200);
});
?>

**Comment by catrielmuller** [comment]
Para usar postman ahora que la API procesa JSON para ser compatible con Ionic, tienes que configuarlo de la siguiente manera. 
![postman](https://cloud.githubusercontent.com/assets/2272323/10893359/23f40156-8187-11e5-8f4a-ad0dd894753b.png)

Tambien te dejo un Screen del Chrome para que veas como ver el Payload que le envia al server.

**Comment by fedemiguez** [comment]
si con postman funciona bien configurando asi, pero no me sale eso del payload 

![image](https://cloud.githubusercontent.com/assets/13700491/10893779/68162a92-8189-11e5-840f-88f9494118f5.png)

que tendria que hacer para solucionarlo?

**Comment by catrielmuller** [comment]
Podrias indicarme el respositorio de tu app de ionic para ver el codigo del post.

**Comment by fedemiguez** [comment]
la app de ionic la tenemos en bitbucket 
https://bitbucket.org/sejuega/se-juega

**Comment by catrielmuller** [comment]
https://bitbucket.org/sejuega/se-juega/commits/1b2121b70c8220d3fd6a43851e9e2b967cdeac9e?at=master
