### ISSUE TITLE
Login con facebook desde mobile

### ISSUE THREAD

**Issue by fedemiguez** [lametro/programacion-4-2015#46]
Hola profe, estamos teniendo un problema con el login de facebook. Desde la pc funciona todo bien el tema es desde el celular. 

Al pricipio me salia este error:

<img src="https://scontent-mia1-1.xx.fbcdn.net/hphotos-xpt1/v/l/t35.0-12/12209361_10208292974141248_608003609_o.jpg?oh=5f166bfbbfe8f71ea2a0b492560ede1b&oe=563B7040">

lo solucione agregandole 'http' a la ruta del js.src que solo tenia // y buscaba esa direccion como un file

pero ahora me aparece un nuevo error 

![image](https://cloud.githubusercontent.com/assets/13700491/10925263/5cfde248-826b-11e5-9e7e-27eb085ca7c9.png)

**Comment by FrancoMeriles** [comment]
A nosotros nos pasa lo mismo profe.

**Comment by catrielmuller** [comment]
Opt1
- http://kmturley.blogspot.com.ar/2014/10/facebook-login-inside-hybrid-app-using.html
- https://github.com/ccoenraets/OpenFB

Opc2
*http://ngcordova.com/
*http://ngcordova.com/docs/plugins/facebook/

Opc3
*http://ngcordova.com/
*http://ngcordova.com/docs/plugins/oauth/
