### ISSUE TITLE
Api Login

### ISSUE THREAD

**Issue by FrancoMeriles** [lametro/programacion-4-2015#47]
Hola profe, este issue es de parte de todos los chicos, @rodriherreria @ignaciopiai @fedemiguez @Franconeri85 @hernanbaigorria @salomonelias  que nos juntamos para ver lo de login pero no podemos lograr que funcione, estos son algunas pruebas que fuimos intentando

``` php

$app->post('/login', function() use ($app) {
    $req = $app->request;

    $user= $req->params('user');
    $pass = $req->params('pass');

    try {
        $query = $app->db->prepare("SELECT user, password FROM users
                              WHERE user = :user AND password = :pass
                              LIMIT 1");
        $query->execute(
            array(
                ':user' => $user,
                ':pass' => $pass)
            )
        );

        $result = $query->fetch();
    }

    catch (PDOException $e) {
        $app->flash('error', 'db error');
    }


    if ( empty($result) ) {
        $app->flash('error', 'wrong user or pass');
        $app->redirect('/login');
    }

    $app->redirect('/');

})->name('login');
```

Login2 esta era una prueba sin la conexion de db pero no toma los valores que enviamos

``` php
$app->post('/login', function () use ($app) {

    $input = $app->request->getBody();
    $errors = array();

    $email = $input['usuario'];
    $password = $input['password'];

    $errors = array();
    if ($email != "puntsdasdasdo@gmail.com") {
        $errors['usuario'] = "Email is not found.";
    } else if ($password != "123") {
        $app->flash('email', $email);
        $errors['password'] = "Password does not match.";
    }

      if (count($errors) > 0) {
        $app->flash('errors', $errors);
        $app->render(200,array('error' => FALSE, 'msg'   => 'Logeado exitosamente',
        ));
    }

});
```

Login 3

``` php
$app->post('/login', function () use ($app) {

    $input = $app->request->getBody();

    $user = $input['usuario'];
    $pass = $input['password'];

    if ($user == "Fran Meriles" && $pass == "1234") { 

            $app->render(200,array('data' => $user->toArray()));    
    }

    $app->render(404,array(
            'error' => TRUE,
            'msg'   => 'user not found',
        ));

    });
```

Login 4

``` php
$app->post('/login', function () use ($app) {

    $input = $app->request->getBody();

    $email = $input['usuario'];

    $user = User::find($email);
    if(empty($user)){
        $app->render(404,array(
            'error' => TRUE,
            'msg'   => 'user not found',
        ));
    }
    $app->render(200,array('data' => $user->toArray()));
});

```

buscamos por todos lados y hay distintas formas o con plugin bastante asperos,

**Comment by catrielmuller** [comment]
He actualizado el repositorio de la API para incorporar un Login y un endpoint con auth.

https://github.com/catrielmuller/api-prog4

Cuando busquen una solución siempre traten de tener presente este principio. https://en.wikipedia.org/wiki/KISS_principle

Les dejo unos screnshots de la nueva funcionalidad de la API
![screen shot 2015-11-12 at 20 47 19](https://cloud.githubusercontent.com/assets/2272323/11135018/0e5d8550-8980-11e5-9f69-5efc5f0ccc75.png)
![screen shot 2015-11-12 at 20 49 38](https://cloud.githubusercontent.com/assets/2272323/11135019/0e5dfc38-8980-11e5-8611-528227485121.png)
![screen shot 2015-11-12 at 20 52 06](https://cloud.githubusercontent.com/assets/2272323/11135020/0e5ff92a-8980-11e5-9b25-a6d905e2381c.png)
![screen shot 2015-11-12 at 20 52 18](https://cloud.githubusercontent.com/assets/2272323/11135021/0e62614c-8980-11e5-8859-77533b77cc65.png)
