### ISSUE TITLE
Consulta bd con tablas relacionadas

### ISSUE THREAD

**Issue by FrancoMeriles** [lametro/programacion-4-2015#49]
Hola profe estamos intentando hacer una consulta a bd para traer el dato de un anuncio especifico pero tmb los datos del usuario que subio ese anuncio para que el que busque el anuncio pueda ponerse en contacto con el dueño. Hasta ahora funciona bien lo del anuncio trae el anuncio especifico pero queremos sumarle q traiga tmb los datos del que publico ese anuncio

Las tablas de la bd son así: 
user: 'id', 'name', 'email', 'tipous', 'passoword'
anuncios: 'id', 'titulo', 'precio', 'descripcion', 'foto', 'barrio', 'usersid'

asi seria mas o menos la consulta

``` sql
SELECT a.id, a.titulo, a.precio, a.descripcion, a.foto, a.barrio, a.usersid, u.id, u.email, u.name
FROM users u, anuncios a
WHERE a.usersid=u.id
```

y cuando traemos un aviso en la api esta así

``` php
$app->get('/anuncios/:id', function ($id) use ($app) {
    $anuncios= Anuncio::find($id);
    if(empty($anuncios)){
        $app->render(404,array(
            'error' => TRUE,
            'msg'   => 'Anuncio no encontrado',
        ));
    }
    $app->render(200,array('data' => $anuncios->toArray()));
});
```

La api: https://github.com/rodriherreria/api-geoalquiler

Si necesita mas datos avísenos.

**Comment by catrielmuller** [comment]
@FrancoMeriles 

Estoy hay muchas formas de resolverlo, la automatica es indicar el campo user de tu modelo de anuncio la relacion para que te traiga automaticamente el usuario.

http://laravel.com/docs/5.1/eloquent-relationships

Tambien puedes hacer una query con un Join.
http://laravel.com/docs/5.1/queries#joins

O por ultimo puedes hacer algo como lo siguiente:

``` php
$anuncio = Anuncio::find($id);
    if(empty($anuncios)){
        $app->render(404,array(
            'error' => TRUE,
            'msg'   => 'Anuncio no encontrado',
        ));
    }
$anuncio->user = User::find($anuncio->userid)
```
