### ISSUE TITLE
Clase Consulta 16/11/15

### ISSUE THREAD

**Issue by catrielmuller** [lametro/programacion-4-2015#50]
https://hangouts.google.com/call/vd3n5unntrzvj6mflpdiov4njqa

**Comment by FrancoMeriles** [comment]
profe puede pushear los ultimos cambios que hizo a la api ? gracias

**Comment by catrielmuller** [comment]
@FrancoMeriles quedo actualizada en la siguiente url https://github.com/catrielmuller/api-prog4
