### ISSUE TITLE
Instalar ionic-autocomplete

### ISSUE THREAD

**Issue by fedemiguez** [lametro/programacion-4-2015#51]
hola profe, intente instalar el plugin de ionic-autocomplete y me sigue pasando lo mismo ya le puse tods las dependencias y cambie los css y js aca una captura de lo que me tira y el link del repo

![image](https://cloud.githubusercontent.com/assets/13700491/11227100/d8c06c8c-8d62-11e5-8b71-46699189e5be.png)

link del repo
https://github.com/fedemiguez/sejuega-autocomplete

**Comment by fedemiguez** [comment]
intente instalar otro plugin con bower que se llama checklist-model que me devuelve los valores de los check en el formato que necesito y todos juntos, pero cuando agrego la dependencia en el app.js no se me rompe la app y sin esa dependencia no funciona tampoco.

![image](https://cloud.githubusercontent.com/assets/13700491/11233781/1eb1043a-8da0-11e5-9fcd-87c2f78d8ee0.png)

dejo el repo actualizado:
https://github.com/fedemiguez/sejuega-autocomplete

**Comment by catrielmuller** [comment]
https://github.com/fedemiguez/sejuega-autocomplete/pull/1
