### ISSUE TITLE
Repositorios actualizados - Problema con el Login

### ISSUE THREAD

**Issue by PixelArg** [lametro/programacion-4-2015#52]
Hola Profesor, disculpe las molestias. Ya actualizamos los repositorios e hicimos el registro pero tuvimos un problema con el login

Aquí están los repositorios:
https://bitbucket.org/pixelesp/api
https://bitbucket.org/pixelesp/aplicacion

Muchas gracias!

**Comment by catrielmuller** [comment]
"NOTICE: Trying to get property of non-object"

Chicos este problema seguramente les va a surgir a todos por lo que presten atención:

``` php
$user = $db->table('usuarios')->select()->where('email', $email)->first();
    if(empty($user)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'user not exist',
        ));
    }

    if($user->password != $password){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'password dont match',
        ));
    }
```

Con la actualizacion de las librerias este codigo no funciona mas ya que el first() no retorna mas un objeto, si no un array. Por lo que cuando queremos usar un atributo de $user deberiamos hacerlo asi.

``` php
$user = $db->table('usuarios')->select()->where('email', $email)->first();
    if(empty($user)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'user not exist',
        ));
    }

    if($user['password'] != $password){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'password dont match',
        ));
    }
```

Tambien podemos hacer un autocast a objeto para no tener que cambiar todo el codigo. agregamos (object) al inicio de la consulta que termina en first();

``` php
$user = (object) $db->table('usuarios')->select()->where('email', $email)->first();
    if(empty($user)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'user not exist',
        ));
    }

    if($user->password != $password){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'password dont match',
        ));
    }
```
