### ISSUE TITLE
Cleardb

### ISSUE THREAD

**Issue by JuampaBlaskovich** [lametro/programacion-4-2015#53]
Profe no podemos subir la base de datos al heroku, porque el ClearDB y Jaws nos piden tarjetas de credito para su instalacion.

**Comment by FrancoMeriles** [comment]
Si, tenes que enlazar una tarjeta de credito, no te va a cobrar nada. todos lo tuvimos que hacer

**Comment by catrielmuller** [comment]
Pueden probar usar un Numero generado automaticamente desde aqui:
http://www.getcreditcardnumbers.com/

Si eso no funciona, y no tienen una tarjeta de credito, avisen me y yo les creo una DB y les paso los accesos por privado.

**Comment by JuampaBlaskovich** [comment]
Gracias!! Tuve que poner una tarjeta
