### ISSUE TITLE
No puedo subir archivos desde Sourcetree al Github

### ISSUE THREAD

**Issue by JuampaBlaskovich** [lametro/programacion-4-2015#54]
![fsdfsdgahfgkjjgljkn](https://cloud.githubusercontent.com/assets/13700584/11260935/958bf638-8e4e-11e5-8286-f1d292f9784f.JPG)

Probamos cambiando todas las contraseñas y que sean iguales en los dos y me sigue tirando el mismo error

**Comment by catrielmuller** [comment]
Open the Hosted Repositories window by clicking View > Show Hosted Repositories or Command + Shift + H.
Click Edit Accounts
Double-click on your GitHub account
Click Set Password

**Comment by JuampaBlaskovich** [comment]
Ahi es para cambiar la constraseña, y me dice que la cotraseña es correcta. Ese no es el problema, nose cual es ni como solucionarlo

**Comment by catrielmuller** [comment]
Probaste haciendo un Clone del repositorio nuevamente?

**Comment by JuampaBlaskovich** [comment]
Si pero sigue tirando lo mismo. No se haga problema vamos a trabajar desde la otra cuenta para no perder tiempo en esto

**Comment by JuampaBlaskovich** [comment]
Ya encontramos el problema. Es entrar en Tools -> Options -> Autenthication (y ahi pusimos en todos la misma contraseña y nos tomo y pudimos pushear todo)
