### ISSUE TITLE
base de datos heroku

### ISSUE THREAD

**Issue by rodrigoliborci** [lametro/programacion-4-2015#56]
profe.. me puede crear una base d datos? ya q no pude validar la cuenta d heroku

**Comment by catrielmuller** [comment]
Rodrigo mandame un email a catrielmuller@gmail.com así te respondo por ahi en privado las credenciales.
Saludos.

**Comment by catrielmuller** [comment]
Las bases de datos en Heroku quedan asociadas unicamente a una App subida con esa cuenta.
Por lo que no puedo generarles DB sin ser el Owner de las Apps.
Lo que pueden hacer es usar este Hosting (http://www.freemysqlhosting.net/) que les deja crear gratuitamente una base de datos mysql. Lo acabo de probar y funciona bien.

**Comment by rodrigoliborci** [comment]
ok! gracias!
