### ISSUE TITLE
inspect devices

### ISSUE THREAD

**Issue by fedemiguez** [lametro/programacion-4-2015#59]
hola profe una pregunta necesito ver que es lo que responde la app y para eso uso el inspect devices pero me aparece solamente el equipo y no la app para poder verla.

![image](https://cloud.githubusercontent.com/assets/13700491/11507573/6450ee22-9833-11e5-9a2a-9eab0c069643.png)

**Comment by catrielmuller** [comment]
Que version del Sistema Operativo estas usando actualmente?

**Comment by catrielmuller** [comment]
Según la documentación oficial, necesitas android 4.4+ para hacer debug de apps.

https://developer.chrome.com/devtools/docs/remote-debugging

Si tienes una versión menor a 4.4 puedes probar instalar este componente para ver si te habilita la opción.

https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

Si no funciona con ello vas a tener que usarlo a traves de un emulador.
