### ISSUE TITLE
Problemas con el Login

### ISSUE THREAD

**Issue by florseg** [lametro/programacion-4-2015#60]
![image](https://cloud.githubusercontent.com/assets/13700600/11535885/aaee26a8-98f4-11e5-8fcd-d5db8895dde2.png)

**Comment by catrielmuller** [comment]
Tu htaccess no esta igual a: https://github.com/catrielmuller/api-prog4/blob/master/.htaccess

Especificamente esta linea

```
Header always set Access-Control-Allow-Headers "auth-token, X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
```

Ya que el error indica que te falta habilitar el Header "auth-token"
