### ISSUE TITLE
Problemas con el Login

### ISSUE THREAD

**Issue by florseg** [lametro/programacion-4-2015#61]
Ya se soluciono ese problema pero todavía nos tira un error con el /me

![image](https://cloud.githubusercontent.com/assets/13700600/11537671/e2b1d064-98fc-11e5-8251-44dd1b14b33a.png)

**Comment by catrielmuller** [comment]
Podrias mostrarme el error que esta arriba del que estas desplegando.

**Comment by florseg** [comment]
![image](https://cloud.githubusercontent.com/assets/13700600/11538007/914f1dc4-98fe-11e5-87fd-bc104a5bd83c.png)

``` php

$app->get('/me', function () use ($app) {

    $token = $app->request->headers->get('auth-token');

    if(empty($token)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'Not logged1',
        ));
    }

    $id_user_token = simple_decrypt($token, $app->enc_key);

    $usuario = User::find($id_user_token);
    if(empty($usuario)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'Not logged2',
        ));
    }
    $app->render(200,array('data' => $usuario->toArray()));
});

```

**Comment by catrielmuller** [comment]
No es un error, es que tu api te esta diciendo que el usuario no esta logueado.
Seguramente estas pasando incorrectamente el token.

**Comment by florseg** [comment]
Hola Profe por el Postman lo envía 
![image](https://cloud.githubusercontent.com/assets/13700600/11542327/a3f80596-9915-11e5-9162-0d0e424c2c60.png)

Pero por la api no 
![image](https://cloud.githubusercontent.com/assets/13700600/11542441/12f30d74-9916-11e5-9476-ce6789f5be13.png)

Subimos el repositorio por las dudas si lo quiere ver 

``` php
$app->post('/login', function () use ($app) {
    $input = $app->request->getBody();

    $email = $input['email'];
    if(empty($email)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'Se requiere el Email',
        ));
    }
    $password = $input['password'];
    if(empty($password)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'Se requiere la Contraseña',
        ));
    }
    $db = $app->db->getConnection();
    $usuario = $db->table('usuarios')->select()->where('email', $email)->first();
    if(empty($usuario)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'El usuario no existe',
        ));
    }
    if($usuario->password != $password){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'La password no coincide',
        ));
    }

    $token = simple_encrypt($usuario->id, $app->enc_key);

    $app->render(200,array('token' => $token));
});

$app->get('/me', function () use ($app) {

    $token = $app->request->headers->get('auth-token');

    if(empty($token)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'Not logged1',
        ));
    }

    $id_user_token = simple_decrypt($token, $app->enc_key);

    $usuario = usuario::find($id_user_token);
    if(empty($usuario)){
        $app->render(500,array(
            'error' => TRUE,
            'msg'   => 'Not logged2',
        ));
    }
    $app->render(200,array('data' => $usuario->toArray()));
});



```

**Comment by catrielmuller** [comment]
@florseg me podes indicar el repositorio donde tienes actualizado el Codigo de la APP. 
Ya que es un problema de la APP, No de la API.

**Comment by florseg** [comment]
Hola profe este es el repo de la app, la tenemos en Bitbucket
https://florseg@bitbucket.org/florseg/glucontroldos.git

2015-12-03 12:28 GMT-03:00 Catriel Müller notifications@github.com:

**Comment by catrielmuller** [comment]
Me pueden brindar un usuario y contraseña de la App que este en su base de datos.

**Comment by florseg** [comment]
Sii Perdón
Flor@gmail.com
12345

Y
lu@gmial.com
12345

**Comment by catrielmuller** [comment]
Por favor solucionen este error en su api como les comente en el TK anterior:

```
XMLHttpRequest cannot load http://api-glucontrol.herokuapp.com/me. Request header field auth-token is not allowed by Access-Control-Allow-Headers in preflight response.
```

Me podes dar permisos a mi usuario catrielmuller de bitbucket asi te hago un commit con la solucion al problema.

**Comment by florseg** [comment]
Ya le mande el permiso profe
https://florseg@bitbucket.org/florseg/glucontroldos.git

2015-12-03 15:58 GMT-03:00 Catriel Müller notifications@github.com:

**Comment by catrielmuller** [comment]
Listo, aqui pueden ver los cambios.

```
https://bitbucket.org/florseg/glucontroldos/commits/074ca611bf7eaeea61b8e4c11c1a1bbea463f51e
```

**Comment by florseg** [comment]
Profe  disculpe las molestias pero seguimos sin poder ingresar a la pagina
de inicio (gallery)
No sabemos donde más buscar, el token ahora por lo menos viaja pero hay una
parte donde no nos deja identificar al usuario y nos revota al usuario.

[image: Imágenes integradas 1]

2015-12-03 17:29 GMT-03:00 Catriel Müller notifications@github.com:

**Comment by catrielmuller** [comment]
Florencia puedes subir la imagen nuevamente ya que no se muestra correctamente.

**Comment by florseg** [comment]
![image](https://cloud.githubusercontent.com/assets/13700600/11593778/e751f494-9a84-11e5-84c1-ad56bd15b8c7.png)

**Comment by florseg** [comment]
buscamos el .htpaccess comparamos y no encontramos error

**Comment by catrielmuller** [comment]
@florseg Podrias indicarme el Repositorio donde tienen alojado la API. (http://api-glucontrol.herokuapp.com/)

**Comment by florseg** [comment]
https://github.com/florseg/api-glucontrol

2015-12-07 22:16 GMT-03:00 Catriel Müller notifications@github.com:

**Comment by catrielmuller** [comment]
Seguramente el problema es por que no actualizaron el codigo en Heroku con un PUSH a heroku.

Subi el codigo a una VM en mi cuenta y funciona perfectamente.
https://infinite-meadow-8843.herokuapp.com/

Con algunas correcciones de código en el index.php

Te dejo un PullRequest aquí:
https://github.com/florseg/api-glucontrol/pull/1

**Comment by LuPicin** [comment]
hola profe disculpe la molestia , el problema  que tenemos ahora es que cuando queremos ingresar con los usuarios que tenemos ya cargados en la base de datos. no tira  error , como que no existen
 ( no da el error que tenemos nosotras en el código , cuando hay algun error en los datos ) .

**Comment by catrielmuller** [comment]
Podrían verificar que los usuarios existan en la Base de Datos y adjuntar el mensaje de error que les retorna la API.

**Comment by LuPicin** [comment]
Si existen en la base de datos. Son los que te paso la otra vez. Y el error
q nos tira es el que pusimos nosotras en el codigo .

**Comment by catrielmuller** [comment]
El problema que estan teniendo ahora lo vimos en clases y es duplicado a la siguiente Issue

https://github.com/lametro/programacion-4-2015/issues/52

**Comment by LuPicin** [comment]
gracias profe !!

2015-12-11 8:48 GMT-03:00 Catriel Müller notifications@github.com:

> Closed #61 https://github.com/lametro/programacion-4-2015/issues/61.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lametro/programacion-4-2015/issues/61#event-489264038
> .

## 

Picin, Luciana

**Comment by florseg** [comment]
La cuestion 52 la vimos el martes con el grupo de pixel art pero ninguna de las 3 nos funciono

y por el momento se ve asi 

 ![image](https://cloud.githubusercontent.com/assets/13700600/11752479/900df076-a01e-11e5-9e81-81d6555243dc.png)

**Comment by LuPicin** [comment]
hola profe nos acabamos de dar cuenta que el 07/12 lanzaron una nueva
version de slim
y cambiaron algunas cosas del codigo. Puede ser por eso que no ande la
parte del login ??
aca esta la url de slim con la nueva version.
http://www.slimframework.com/2015/12/07/slim-3.html

2015-12-11 16:02 GMT-03:00 Florencia notifications@github.com:

> La cuestion 52 la vimos el martes con el grupo de pixel art pero ninguna
> de las 3 nos funciono
> 
> y por el momento se ve asi
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/13700600/11752479/900df076-a01e-11e5-9e81-81d6555243dc.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lametro/programacion-4-2015/issues/61#issuecomment-164019147
> .

## 

Picin, Luciana

**Comment by catrielmuller** [comment]
El problema surge de un cambio de política de Heroku de implementar por defecto PHP7 el cual no es compatible con el código que estuvimos viendo.

```
remote:        - php (7.0.0)
remote:        - Apache (2.4.16)
remote:        - Nginx (1.8.0)
```

Por lo que es necesario especificar la versión de PHP que necesitamos usar.
Para hacerlo modificamos el archivo composer.json como lo hice aquí:

https://github.com/catrielmuller/api-glucontrol/blob/master/composer.json

Luego hacemos un update con el comando:

```
composer update
```

Para que actualice el archivo composer.lock

Luego de eso cuando hagamos un deploy a Heroku vamos a ver que instala php5

```
remote: -----> Installing system packages...
remote:        - php (5.6.16)
remote:        - Apache (2.4.16)
remote:        - Nginx (1.8.0)
```

Utilizando el comando heroku logs. Podemos ver los errores que se producen en el Server de Heroku por si no sabemos por que nos tira un error 500.

Saludos.

**Comment by florseg** [comment]
Renegamos pero funciona
Muchas Gracias  Profe :)
Seguramente mañana o pasado volverá a recibir noticias nuestras con alguna
consulta.
